version: '3.8'
services:
  tags:
    image: pukala93/tags-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    volumes: 
      - ./scripts:/docker-entrypoint-initdb.d